OnlineShopping/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShopping.Data;
using OnlineShopping.Models;

namespace OnlineShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;
        public ProductsController(ApplicationDbContext db,IHostingEnvironment he )
        {
            _db = db;
            _he = he;
        }
        //GET Index action method
        public IActionResult Index()
        {
            return View(_db.Products.Include(c=>c.ProductTypes).Include(f=>f.TagNames).ToList());
        }

        //POST Index action method
        [HttpPost]
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.TagNames)
                .Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if (lowAmount == null || largeAmount == null)
            {
                products = _db.Products.Include(c => c.ProductTypes).Include(c => c.TagNames).ToList();
            }
            return View(products);
        }

        //Create GET Action Method
        public IActionResult Create()
        {
            ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(),"ID", "ProductType");
            ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
            return View();
        }

        //Create POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Products products,IFormFile image)
        {
            if (ModelState.IsValid)
            {

                var searchproduct = _db.Products.FirstOrDefault(c=>c.Name==products.Name);
                if(searchproduct!=null)
                {
                    ViewBag.msg = "This Product is already exist.";
                    ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(), "ID", "ProductType");
                    ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
                    return View(products);
                }

                if(image!=null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images" , Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if(image==null)
                {
                    products.Image = "Images/No-image-found.jpg";
                }

                _db.Products.Add(products);
                await _db.SaveChangesAsync();
                TempData["Save"] = "Product Type Has been Saved";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(products);
        }

        //Edit GET Action Method
        public IActionResult Edit(int? id)
        {
            ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(), "ID", "ProductType");
            ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
            if (id == null)
            {
                return NotFound();
            }

            var product = _db.Products.Include(c=>c.ProductTypes).Include
                              (c=>c.TagNames).FirstOrDefault(c=>c.ID==id);

            if(product==null)
            {
                return NotFound();
            }
            return View(product);
        }

        //Edit POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Products products, IFormFile image)
        {
            if (ModelState.IsValid)
            {

                var searchproduct = _db.Products.FirstOrDefault(c => c.Name == products.Name);
                if (searchproduct != null)
                {
                    ViewBag.msg = "This Product is already exist.";
                    ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(), "ID", "ProductType");
                    ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
                    return View(products);
                }

                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/No-image-found.jpg";
                }

                _db.Products.Update(products);
                await _db.SaveChangesAsync();
                TempData["Edit"] = "Product Type Has been Updated";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(products);
        }

        //Details GET Action Method
        public IActionResult Details(int? id)
        {
            ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(), "ID", "ProductType");
            ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include
                              (c => c.TagNames).FirstOrDefault(c => c.ID == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //Details POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(Products products)
        {
            return RedirectToAction(actionName: nameof(Index));
        }


        //Delete GET Action Method
        public IActionResult Delete(int? id)
        {
            ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(), "ID", "ProductType");
            ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include
                              (c => c.TagNames).FirstOrDefault(c => c.ID == id);

            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //This one also work.....

        ////Delete POST Action Method
        //[HttpPost]
        //[ActionName("Delete")]
        //public async Task<IActionResult> DeleteConfirm(int? id)
        //{
        //    ViewData["ProductType"] = new SelectList(_db.ProductTypes.ToList(), "ID", "ProductType");
        //    ViewData["TagName"] = new SelectList(_db.TagNames.ToList(), "ID", "TagName");
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var product = _db.Products.FirstOrDefault(c => c.ID == id);
        //    if (product == null)
        //    {
        //        return NotFound();
        //    }
        //    _db.Products.Remove(product);
        //    await _db.SaveChangesAsync();
        //    //TempData["Delete"] = "Product Type Has been Deleted";
        //    return RedirectToAction(actionName: nameof(Index));
        //}

        //Delete POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, Products products)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return NotFound();
                }
                if (id != products.ID)
                {
                    return NotFound();
                }
                var product = _db.Products.Find(id);
                if (product == null)
                {
                    return NotFound();
                }

                _db.Products.Remove(product);
                await _db.SaveChangesAsync();
                TempData["Delete"] = "Product Type Has been Deleted";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(products);
        }

    }
}

OnlineShopping/Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineShopping.Areas.Admin.Models;
using OnlineShopping.Data;

namespace OnlineShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        ApplicationDbContext _db;
        public RoleController(RoleManager<IdentityRole> roleManager, ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _db = db;

            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.Roles = roles;
            return View();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Role has been saved successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string name)
        {

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["Edit"] = "Role has been updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                TempData["Delete"] = "Role has been deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }



        public async Task<IActionResult> Assign()
        {
            ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(RoleUserVm roleUser)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(c => c.Id == roleUser.UserId);
            var isCheckRoleAssign = await _userManager.IsInRoleAsync(user, roleUser.RoleId);
            if (isCheckRoleAssign)
            {
                ViewBag.mgs = "This user already assign this role.";
                ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
                ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
                return View();
            }
            var role = await _userManager.AddToRoleAsync(user, roleUser.RoleId);
            if (role.Succeeded)
            {
                TempData["Save"] = "User Role assigned.";
                return RedirectToAction(nameof(AssignUserRole));
            }
            return View();
        }

        public ActionResult AssignUserRole()
        {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join a in _db.ApplicationUsers on ur.UserId equals a.Id
                         select new UserRoleMaping()
                         {
                             UserId = ur.UserId,
                             RoleId = ur.RoleId,
                             UserName = a.UserName,
                             RoleName = r.Name
                         };
            ViewBag.UserRoles = result;
            return View();
        }

        public async Task<IActionResult> DeleteAssignRole(string id)
        {
            ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAssignRole(RoleUserVm roleUser)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(c => c.Id == roleUser.UserId);
            var isCheckRoleAssign = await _userManager.IsInRoleAsync(user, roleUser.RoleId);

            var role = await _userManager.RemoveFromRoleAsync(user, roleUser.RoleId);
            if (role.Succeeded)
            {
                TempData["Delete"] = "User Role Deleted.";
                return RedirectToAction(nameof(AssignUserRole));
            }
            return View();
        }

    }
}

OnlineShopping/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <td style="width:170px;">
        <div class="form-group">
            <a asp-action="Edit"  class="btn btn-warning" asp-route-id="@Model"><i class="fas fa-edit"></i></a>
            <a asp-action="Details"  class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
            <a asp-action="Delete"  class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></a>
        </div>
    </td>

OnlineShopping/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using OnlineShopping.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
        products = new List<Products>();
    }
    count = products.Count();

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    </environment>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == "Admin")
                        {
                            <navbar>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>

                                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                                        <li class="nav-item dropdown dmenu">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                                Types
                                            </a>
                                            <div class="dropdown-menu sm-menu">
                                                <div class="nav-link text-dark"></div>
                                                <a class="dropdown-item" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
                                                <a class="dropdown-item" asp-area="Admin" asp-controller="TagNames" asp-action="Index">Tag Names</a>
                                            </div>
                                        </li>
                                        <li class="nav-item dropdown dmenu">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                                Stocks
                                            </a>
                                            <div class="dropdown-menu sm-menu">
                                                <div class="nav-link text-dark"></div>
                                                <a class="dropdown-item" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                                                <a class="dropdown-item" asp-area="Customer" asp-controller="Orders" asp-action="Index">Orders</a>
                                            </div>
                                        </li>
                                        <li class="nav-item dropdown dmenu">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                                Users Info
                                            </a>
                                            <div class="dropdown-menu sm-menu">
                                                <div class="nav-link text-dark"></div>
                                                <a class="dropdown-item" asp-area="Customer" asp-controller="User" asp-action="Index">Customer</a>
                                                <a class="dropdown-item" asp-area="Admin" asp-controller="Role" asp-action="Index">Role</a>
                                                <a class="dropdown-item" asp-area="Admin" asp-controller="Role" asp-action="AssignUserRole">AssignUserRole</a>
                                            </div>
                                        </li>

                                    </ul>

                                </div>
                            </navbar>
                        }


                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="TagNames" asp-action="Index">Tag Names</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Customer" asp-controller="User" asp-action="Index">Customer</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="Index">Role</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="AssignUserRole">AssignUserRole</a>
        </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#">Contact Us</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" href="#">Call</a>
                        </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                                <i class="fas fa-shopping-cart"></i>
                                (@count)
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        @*<script src="https://code.jquery.com/jquery-3.3.1.js"></script>*@
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    </environment>
    <environment exclude="Development">
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>*@

        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>


    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

OnlineShopping/Views/Shared/_PartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:200px;">
    <div class="form-group">
        <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model"><i class="fas fa-edit"></i></a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></a>
        <a asp-action="Locout" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-lock"></i></a>
    </div>
</td>